apiVersion: v1
kind: Service
metadata:
  name: "{{ include "example-rollouts.fullname" . }}-preview"
  labels:
    {{- include "example-rollouts.labels-preview" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "example-rollouts.selectorLabels-preview" . | nindent 4 }}
